# Generated by Django 5.2.6 on 2025-09-13 20:40

import creditcards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_address', models.CharField(max_length=150)),
                ('shipment_phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='crowdfunding.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=20)),
                ('shipment_address', models.CharField(blank=True, max_length=150, null=True)),
                ('shipment_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', creditcards.models.CardNumberField(blank=True, max_length=25, null=True)),
                ('expire', creditcards.models.CardExpiryField(blank=True, null=True)),
                ('security_code', creditcards.models.SecurityCodeField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crowdfunding.donation')),
            ],
        ),
    ]
